spring:
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 1157479142@qq.com #发送邮件的邮箱地址
    password: dynieqhokrgribff

    from: 1157479142@qq.com # 发送邮件的地址，和上面username一致
    properties:
          mail:
            #配置SSL 加密工厂
            smtp:
              ssl:
                #本地测试，先放开ssl
                enable: true
                required: true
              #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
            debug: true
    default-encoding: utf-8
#spring:
#  #邮箱基本配置
#  mail:
#    #配置smtp服务主机地址
#    # qq邮箱为smtp.qq.com          端口号465或587
#    # sina    smtp.sina.cn
#    # aliyun  smtp.aliyun.com
#    # 163     smtp.163.com       端口号465或994
#    host: smtp.qq.com
#    #发送者邮箱
#    username: 1157479142@qq.com
#    #配置密码,注意不是真正的密码，而是刚刚申请到的授权码
#    password: dynieqhokrgribff
#    #端口号465或587
#    port: 587
#    #默认的邮件编码为UTF-8
#    default-encoding: UTF-8
#    #其他参数
#    properties:
#      mail:
#        #配置SSL 加密工厂
#        smtp:
#          ssl:
#            #本地测试，先放开ssl
#            enable: true
#            required: true
#          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
#        debug: true